version: '2'
services:
  swarm-alert:
    image: gpulidodt/swarm-alert:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUSHOVER_USER_KEY: "user_key_from_pushover"
      PUSHOVER_API_TOKEN: "your_app_token_from_pushover"
      MSG_PREFIX: "$MSG_PREFIX"
