version: '2'
services:
  swarm-alert:
    image: gpulidodt/swarm-alert:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUSHOVER_APP_KEY: "XXX"
      PUSHOVER_TOKEN: "$SLACK_TOKEN"
      MSG_PREFIX: "$MSG_PREFIX"
